# Generated by Django 6.1 on 2026-09-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_chat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
