# Generated by Django 6.1 on 2026-09-01 14:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_messageread'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message', '-created_at'], name='accounts_at_message_153e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', '-created_at'], name='accounts_ch_type_32b599_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['user', '-joined_at'], name='accounts_ch_user_id_d6676d_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmember',
            index=models.Index(fields=['chat', 'role'], name='accounts_ch_chat_id_d25821_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='accounts_me_chat_id_46b8ca_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='accounts_me_sender__c9f4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'is_deleted', '-created_at'], name='accounts_me_chat_id_3ff0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['message', '-read_at'], name='accounts_me_message_794453_idx'),
        ),
    ]
